language: java
env: 
  - CONTAINER=JBOSS_AS_MANAGED_7.X
  - CONTAINER=GLASSFISH_MANAGED_3.1
script: "mvn -P ${CONTAINER} install"
jdk:
  - oraclejdk7
  - openjdk6
matrix:
  exclude:
    - env: CONTAINER=GLASSFISH_MANAGED_3.1
      jdk: openjdk6
notifications:
  email: false
  irc: "chat.freenode.net#ocpsoft"

