language: java
jdk: openjdk6
env: 
  - CONTAINER=JBOSS_AS_MANAGED_7.X
  - CONTAINER=WILDFLY_MANAGED_8
  - CONTAINER=GLASSFISH_MANAGED_3.1
  - CONTAINER=TOMEE_MANAGED_1.5
script: "mvn -P ${CONTAINER} install"
matrix:
  include:
    - env: CONTAINER=JBOSS_AS_MANAGED_7.X
      jdk: oraclejdk7
notifications:
  email: false
  irc: "chat.freenode.net#ocpsoft"

