language: java
script: "mvn -P ${CONTAINER} install"
matrix:
  # exclude default build as we manually define the build matrix
  # see: https://github.com/travis-ci/travis-ci/issues/1228
  exclude:
    - env: ""
      jdk: ""
  include:
    - env: CONTAINER=JBOSS_AS_MANAGED_7.X
      jdk: openjdk6
    - env: CONTAINER=JBOSS_AS_MANAGED_7.X
      jdk: oraclejdk7
    - env: CONTAINER=WILDFLY_MANAGED_8
      jdk: oraclejdk7
    - env: CONTAINER=GLASSFISH_MANAGED_3.1
      jdk: openjdk6
    - env: CONTAINER=TOMEE_MANAGED_1.5
      jdk: openjdk6
  allow_failures:
    - env: CONTAINER=GLASSFISH_MANAGED_3.1
      jdk: openjdk6
    - env: CONTAINER=WILDFLY_MANAGED_8
      jdk: oraclejdk7
notifications:
  email: false
  irc: "chat.freenode.net#ocpsoft"

