language: java
jdk: openjdk6
env: 
  - CONTAINER=JBOSS_AS_MANAGED_7.X
  - CONTAINER=GLASSFISH_MANAGED_3.1
  - CONTAINER=TOMEE_MANAGED_1.5
script: "mvn -P ${CONTAINER} install"
matrix:
  include:
    - env: CONTAINER=WILDFLY_MANAGED_8
      jdk: oraclejdk7
    - env: CONTAINER=GLASSFISH_MANAGED_4.0
      jdk: oraclejdk7
  allow_failures:
    - env: CONTAINER=GLASSFISH_MANAGED_4.0
      jdk: oraclejdk7
notifications:
  email:
    - "ocpsoft-ci@googlegroups.com"
  irc:
    - "chat.freenode.net#ocpsoft"

